// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huxyvrnwefkedmdxjkep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1eHl2cm53ZWZrZWRtZHhqa2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzIyMTYsImV4cCI6MjA3MjY0ODIxNn0.7XUaSTS2s91sYXCXDqE0M_zTKJgkU5LKZyJIgeKTACY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});